version: '3'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # 실제 .env 파일을 컨테이너의 /app/app/.env 경로에 마운트
      - ./app/.env:/app/app/.env
    restart: unless-stopped
    # 환경 변수를 여기에 직접 설정할 수도 있습니다
    # environment:
    #   - SUPABASE_URL=your_supabase_url
    #   - SUPABASE_KEY=your_supabase_key
    #   - GEMINI_API_KEY=your_gemini_api_key 